dist: trusty
sudo: false
language:
  - node_js
node_js:
  - '7'
env:
  - TERM=dumb
before_install:
  - git fetch --unshallow
install:
  - cd web && npm run init
after_success:
  - git status
cache:
  directories:
  - cnf/cache/stable
addons:
  sonarcloud:
    organization: "fswt-github" # the key of the org you chose at step #3
script:
  - cd ../web && mocha -r ts-node/register -r ignore-styles src/**/*.spec.ts
  - cd ..  
  - sonar-scanner -Dsonar.projectKey=fswt_specmate -Dsonar.sources=/home/travis/build/fswt/specmate/web/src
